### PR TITLE
DFDL Intellisense

### PR DESCRIPTION
**Pull request by Shanedell**
This PR wires up Regis's DFDL intellisense/language extension

### CODE REVIEW

**Review by scholarsmate — APPROVED** [review]

**Comment by rt320** [comment]
I checked out the code for the pull request. But when I run in debug I don't get the same items returned as I do when I run the intellisense extension on its own.  Here is what I see when I run the code from the daffodil-vscode dfdl-intellsense fork.
image
Here is what I see when I run the dfdl intellsense extension
image

**Comment by Shanedell** [comment]
@rt320 I get the same result as you get when running just the intellisense on its own. Question do you have a version of daffodil-vscode extension installed currently? If so uninstall it, there could different ones installed depending, reload vscode and relaunch the debugging as this could be causing your issues.

**Comment by Shanedell** [comment]
Yeah that is correct, that email was wrong. I made a mistake and made the PR go to the Apache repo at first then fixed it to be to the CTC repo which is 45.

**Comment by rt320** [comment]
OK, I closed and opened VS Code.  I checked installed extensions, but dfdl-intellisense wasn't installed. When I ran the forked code in debug this time, it mostly worked, although I did get duplicate entries for the two items.  I'll look at that and the colorization (which worked in the dfdl-intellisense extension). Thanks for your help!
image

**Comment by Shanedell** [comment]
So I didn't mean check if intellisense was installed but there was an extension installed called `Apache Daffodil VS Code Extension` if so that needs uninstalled.

**Comment by rt320** [comment]
I checked for the Apache Daffodil VS Code Extension, but I didn't have that installed either.

**Comment by Shanedell** [comment]
@rt320 I checked out this code everything looks good, if I go through and just fix up the issues with CI is good to be merged or are you still updating?

**Comment by scholarsmate** [comment]
@Shanedell and @rt320, is this PR overtaken by events (OBE) with the merge of https://github.com/ctc-oss/daffodil-vscode/pull/49?  If so, let's close it.

**Pull request closed without merging**
